# Generated by Django 4.0.4 on 2022-11-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='プラン番号')),
                ('plan_title', models.TextField(max_length=20, verbose_name='プランタイトル')),
                ('plan_num', models.IntegerField(verbose_name='プラン人数')),
                ('plan_content', models.TextField(max_length=50, verbose_name='プラン内容')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='部屋番号')),
                ('room_num', models.IntegerField(verbose_name='部屋人数')),
                ('room_type', models.TextField(max_length=5, verbose_name='部屋タイプ')),
                ('room_detail', models.TextField(max_length=40, verbose_name='部屋詳細')),
                ('room_date1', models.DateField(verbose_name='禁止開始日')),
                ('room_date2', models.DateField(verbose_name='禁止終了日')),
            ],
        ),
        migrations.CreateModel(
            name='Yoyaku',
            fields=[
                ('yoyaku_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='予約番号')),
                ('yoyaku_person', models.IntegerField(verbose_name='予約者')),
                ('yoyaku_date', models.DateField(verbose_name='予約日')),
                ('yoyaku_room', models.TextField(max_length=5, verbose_name='予約部屋')),
                ('yoyaku_num', models.IntegerField(verbose_name='予約人数')),
                ('yoyaku_plan', models.IntegerField(verbose_name='予約プラン')),
                ('yoyaku_bikou', models.TextField(max_length=50, verbose_name='要望事項等')),
                ('yoyaku_update', models.DateTimeField(auto_now_add=True, verbose_name='予約更新日時')),
            ],
        ),
    ]
