# Generated by Django 4.1.3 on 2022-11-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calendar_day', models.DateField(primary_key=True, serialize=False, verbose_name='日付')),
                ('calendar_holiday', models.TextField(choices=[(0, '平日'), (1, '休日')], default=0, max_length=1, verbose_name='休日')),
                ('calendar_sagaku', models.TextField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=1, verbose_name='差額')),
            ],
        ),
    ]
