# Generated by Django 4.1.3 on 2022-12-10 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_calendar_calendar_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sagaku',
            fields=[
                ('sagaku_type', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='差額タイプ')),
                ('sagaku_charge', models.IntegerField(verbose_name='差額料金')),
                ('sagaku_comment', models.TextField(max_length=20, verbose_name='差額説明')),
                ('sagaku_update', models.DateTimeField(auto_now_add=True, verbose_name='差額更新日時')),
            ],
        ),
        migrations.AlterField(
            model_name='calendar',
            name='calendar_sagaku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.sagaku', verbose_name='差額タイプ'),
        ),
    ]
